#!/usr/bin/env bash

tput civis; for i in $(seq 0 $(tput cols)); do for j in {0..10}; do printf "%$(($i*$RANDOM%100))s\n" "-" | sed "s/-/>/g" | sed "s/ /-/g"; done; sleep 0.05; clear; done; clear; tput cnorm
