#!/usr/bin/env bash

tput civis; for x in $(seq 0 $(($(tput lines)-2))); do clear; jj=$x; j=$jj; c=0; while ((c++,j--)); do printf "%$(($j+1))s%$(($c*2))s\n" "/" "\\"; done; sleep 0.03; for k in $(seq 0 $(($jj+$c-1))); do printf "%s" "-"; done; echo; done; tput cnorm
